version: "3.9"

services:
  niq-dev-core:
    build:
      context: .
      dockerfile: default.Dockerfile
    container_name: niq-dev-core
    ports:
      - '8000:8080'
    networks:
      - niq-dev-internal

networks:
  niq-dev-internal:
    external: true